//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleSearchApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class peopleSearchApplicationTable
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public System.DateTime DOB { get; set; }
        public string interests { get; set; }
        public string personID { get; set; }
    }
}
